runner:
    timeout_after_max_speed: 0.5
    timeout_after_complete: 3
    timeout_check_goal: 2

interpreters:
  velocity_interpreter_node: # node name
    max_vel: 0.8
    rate: 100

calculators:
  file_prefix: "test" # All calculators will prefix this to filenames that they write to.
  dest_dir: "/home/rachel/ARAIG"
  robot_type: "turtlebot3_sim"
  test_type: "test1_braking"

  test_comp_param_node: # node name 
    param: 0.0
    tolerance: 0.5

  test_comp_poses_node: # node name 
    pose_tolerance: 0.0
    orientation_tolerance: None
  
  test_comp_topics_node: # node name 
    tolerance: 0

  test_bagger:
    start_offset: 2 # Wait these many seconds before killing
    stop_offset: 2 # Wait these many seconds before killing
    blacklist: # Any topics which have one of these STRINGS in them will not be recorded by the rosbagger
      - /compressedDepth

  rosparam_logger_node:
    start_offset: 1
    stop_offset: 0.5
    namespaces:
      - "runner"
      - "interpreters"
      - "calculators"

  results_logger_node:
    start_offset: 0.5
    stop_offset: 0.1
    logginng_topics:
      - /data/calc/braking_time
      - /data/calc/braking_distance
